server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    username: root
    password: 123456
    url: jdbc:mysql://www.lzuwk.ltd:3306/library?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mabatis/mappers/*.xml
  type-aliases-package: com.wk.vo
  configuration:
    map-underscore-to-camel-case: false